### ISSUE TITLE
ImportError: libipopt.so.1

### ISSUE THREAD

**Issue by ghost** [xuy/pyipopt#13]
Eric,

I'm not able to run 'hs071.py' example... I've got problems in importing 'pyipoptcore'...

I've checked my IPOPT as described in Troubleshooting section and it worked fine.

By running 'python hs071.py' I've got the following error:
  File "hs071.py", line 6, in <module>
    import pyipopt
  File "/usr/local/lib/python2.7/dist-packages/pyipopt/**init**.py", line 12, in <module>
    from pyipoptcore import *
ImportError: libipopt.so.1: cannot open shared object file: No such file or directory

May be important to report that when I've built pyipopt I've got some warnings, mainly concerning NumPy:
$ python setup.py build
running build
running build_py
running build_ext
building 'pyipoptcore' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/coin/ -I/usr/include/python2.7 -c src/callback.c -o build/temp.linux-x86_64-2.7/src/callback.o
In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1728:0,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:15,
                 from src/hook.h:7,
                 from src/callback.c:36:
/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_deprecated_api.h:11:2: warning: #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
  ^
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/coin/ -I/usr/include/python2.7 -c src/pyipoptcoremodule.c -o build/temp.linux-x86_64-2.7/src/pyipoptcoremodule.o
In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1728:0,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:15,
                 from src/hook.h:7,
                 from src/pyipoptcoremodule.c:9:
/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_deprecated_api.h:11:2: warning: #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
  ^
src/pyipoptcoremodule.c: In function ‘set_intermediate_callback’:
src/pyipoptcoremodule.c:470:15: warning: variable ‘myowndata’ set but not used [-Wunused-but-set-variable]
  DispatchData myowndata;
               ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/callback.o build/temp.linux-x86_64-2.7/src/pyipoptcoremodule.o -L/usr/local/lib -lipopt -lblas -lcoinmumps -lcoinmetis -llapack -ldl -lm -o build/lib.linux-x86_64-2.7/pyipopt/pyipoptcore.so

Cheers!

**Comment by nanthony21** [comment]
Same issue here. Do I just manually copy libipopt to the pyipopt directory?

**Comment by AntonioRamalho96** [comment]
Hey! I had the same error, the "ldconfig trick" didn't work for me as well but I managed to work around it.
So the file that I was missing was **libpopt.so.0**, it was in the directory:
`$BUILDDIR/lib`
**$BUILDDIR** corresponds to the directory were ipopt was built.
I added this directory to the file **etc/ld.so.conf**, I did this by adding this line to the file:
`include $BUILDDIR/lib/libopt.so.0`
Afterwords I ran the command:
`sudo ldconfig #I suppose this updates ld.so.cache` 
Then I re-installed pyipopt and it worked!! I hope this helps others!

EDIT: I encountered the same problem in another computer, my solution didn't work but I found this link:
[how to fix shared object file](https://codeyarns.com/2014/01/14/how-to-fix-shared-object-file-error/)
The **Add to LD_LIBRARY_PATH** approach worked for me!
