### ISSUE TITLE
Symbol not found: _PyInt_AsLong in python3

### ISSUE THREAD

**Issue by Balandat** [xuy/pyipopt#17]
Thanks a lot for adding python 3 support. Compiling and installing works fine, but I do get the following error when trying to import pyipopt (pyipopt runs great under python 3.7 with the same ipopt library): 

import pyipopt
ImportError                               Traceback (most recent call last)
<ipython-input-1-d53c3bfda105> in <module>()
----> 1 import pyipopt
/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyipopt/__init__.py in <module>()
     14 
     15 from ipoptconst import *
---> 16 from pyipoptcore import *
     17 from ipoptunconstrained import fmin_unconstrained
     18 
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyipopt/pyipoptcore.so, 2): Symbol not found: _PyInt_AsLong
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyipopt/pyipoptcore.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyipopt/pyipoptcore.so

**Comment by chenruizhi59** [comment]
Just changed PyInt to PyLong in callback.c
