### ISSUE TITLE
trying to install on mac os x

### ISSUE THREAD

**Issue by jacobsca** [xuy/pyipopt#19]
I am having difficulty with the install. I pulled a binary of ipopt and edited setup.py but have an error on the build...

-----------

/usr/bin/clang -bundle -undefined dynamic_lookup -L/opt/local/lib -Wl,-headerpad_max_install_names -L/opt/local/lib/db48 build/temp.macosx-10.10-x86_64-2.7/src/callback.o build/temp.macosx-10.10-x86_64-2.7/src/pyipoptcoremodule.o -L/Users/clasajacobson/ipopt/lib -lipopt -lblas -lcoinmumps -lcoinmetis -llapack -ldl -lm -o build/lib.macosx-10.10-x86_64-2.7/pyipopt/pyipoptcore.so
ld: library not found for -lcoinmetis
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/usr/bin/clang' failed with exit status 1

**Comment by xuy** [comment]
This is a non-issue. Please see the README file. You will need to compile Ipopt from source code to get those coin libraries, such as coinmetis.
