### ISSUE TITLE
loading pyipopt...

### ISSUE THREAD

**Issue by jacobsca** [xuy/pyipopt#20]
I got everything to compile (under python 2.7) but get the following when i try to run the example - this is related to an issue posted but I don't see an obvious fix...

----------

Class-MBP:examples clasajacobson$ python hs071.py
Traceback (most recent call last):
  File "hs071.py", line 6, in <module>
    import pyipopt
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyipopt/__init__.py", line 16, in <module>
    from pyipoptcore import *
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyipopt/pyipoptcore.so, 2): Symbol not found: __ZNSs4_Rep20_S_empty_rep_storageE
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyipopt/pyipoptcore.so
  Expected in: flat namespace
 in /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyipopt/pyipoptcore.so

**Comment by xuy** [comment]
Please refer to the Readme file for more information. Basically -lstdc++ is missing during compilation.
