### ISSUE TITLE
segmentation fault occurred when use pyipopt

### ISSUE THREAD

**Issue by lwan86** [xuy/pyipopt#24]
I'm trying to use the pyipopt to solve an NLP problem. After I executed the python code, a segmentation fault occurred. The following are the returned information:

[PyIPOPT] Ipopt will use Hessian approximation.

[PyIPOPT] Problem created

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.12.4, running with linear solver ma27.

[Callback:E] eval_jac_g
[PyIPOPT] return from eval_jac_g is null

I was wondering if someone has any clue about why this happened.

**Comment by xuy** [comment]
There is not enough information to reproduce the issue. Please paste the python problem here if possible. Mean while, check if your eval_jac_g routing is indeed returning the result of right size.

**Comment by lwan86** [comment]
Hi Dr. Xu,

Thanks for your reply!
The following is the python code I wrote:


****************************************************************************
    def eval_f(self, x, user_data = None):
        a = user_data['a']
        b = user_data['b']
        return sum([a[i]*b[i]*(x[i]) for i in range(len(a))])

    def eval_grad_f(self, x, user_data = None):
        a = user_data['a']
        b = user_data['b']
        return array([a[i]*b[i] for i in range(len(a))], float_)

    def eval_g(self, x, user_data= None):
        c = user_data['c']
        d = user_data['d']
        e = user_data['e']
        f = user_data['f']
        return sum([c[i]*(d[i]*e[i]/x[i]-0.5*x[i])/(e[i]-f[i]) for i in
range(len(c))])

    def eval_jac_g(self, x, flag, user_data = None):
        if flag:
            return (array([0, 0, 0, 0]),
array([0, 1, 2, 3]))
        else:
            c = user_data['c']
            d = user_data['d']
            e = user_data['e']
            f = user_data['f']
            return array([c[i]*(-d[i]*e[i]/(x[i]**2)-0.5)/(e[i]-f[i]) for i
in range(len(c))], float_)

   def optimization(self, a, b, c, d, e, f):
         user_data = {}
         user_data['c'] = c
         user_data['a'] = a
         user_data['d'] = d
         user_data['f'] = f
         user_data['d'] = d
         user_data['b'] = b
         x_low = array([math.sqrt(2*d[i]*f[i]) for i in in range(len(d))])
         x_up = array([math.sqrt(2*d[i]*e[i]) for i in in range(len(d))])
         cons_low = array([0.0])
         cons_up = array([51200/24.0])
         nvars = len(a)
         ncons = 1
         nnzjac = len(a)
         nnzhess = (nvars**2+nvars)/2
         nlp = pyipopt.create(nvars, x_low, x_up, ncons, cons_low, cons_up,
nnzjac, nnzhess, self.eval_f, self.eval_grad_f, self.eval_g,
self.eval_jac_g)
         x0 = array([math.sqrt(2*d[i]*(0.1*f[i]+0.9*e[i])) for i
in range(len(d))])
         x, zl, zu, constraint_multipliers, obj, status = nlp.solve(x0,
user_data)

****************************************************************************

Lipeng
