### ISSUE TITLE
repeated "PyDebug" output

### ISSUE THREAD

**Issue by economoser** [xuy/pyipopt#38]
I apologize in advance for being new to the pyipopt interface -- thank you for the incredible work on this project. I run a simple instance of a NLP that I want to solve using IPOPT via pyipopt. The output from the IPOPT solver command

`x, zl, zu, constraint_multipliers, obj, status = nlp.solve(x0)`

is severely contaminated with lines of

`PyDebug NUMBER`

, where NUMBER is a 6-decimal place number such as 0.000000 or 21.746642. The above line is printed several hundreds of times as part of the output, approximately 150 times before the derivative checker and problem summary, and another 18 times between each iteration. I noticed that for larger scale problems, the frequency of the "PyDebug" output goes up, much faster than the number of iterations, and this starts to occupy a lot of clock time very quickly.

Some sample output from my actual program (I am happy to post the relevant parts of it if you think that helps, but it is fairly standard). Note, however, that when running the example file "hs071_PY3.py", I do not get any "PyDebug" output. I wonder what is causing the above output, and how I can suppress it (or what I should do to fix the underlying problem)?

`******************************************************************************`
`This program contains Ipopt, a library for large-scale nonlinear optimization.`
` Ipopt is released as open source code under the Eclipse Public License (EPL).`
`         For more information visit http://projects.coin-or.org/Ipopt`
`******************************************************************************`
 
This is Ipopt version 3.12, running with linear solver ma27.
 
Starting derivative checker for first derivatives.
 
Starting derivative checker for second derivatives.
 
[Logspam] built arglist for eval_h
[Logspam] Python function eval_h returns non-NULL
PyDebug 0.000000
PyDebug 0.000000
[...many more lines of this and similar ones...]
PyDebug 0.000000
 
No errors detected by derivative checker.
 
[Logspam] built arglist for eval_h
[Logspam] Python function eval_h returns non-NULL
Number of nonzeros in equality constraint Jacobian...:       18
Number of nonzeros in inequality constraint Jacobian.:      180
Number of nonzeros in Lagrangian Hessian.............:       18
 
Total number of variables............................:       18
variables with only lower bounds:       18
variables with lower and upper bounds:        0
variables with only upper bounds:        0

Total number of equality constraints.................:        1
Total number of inequality constraints...............:       30
inequality constraints with only lower bounds:        0
inequality constraints with lower and upper bounds:        0
inequality constraints with only upper bounds:       30

PyDebug 1.969484
PyDebug 1.790440
PyDebug 1.392636
PyDebug 1.969484
PyDebug 1.790440
PyDebug 1.392636
PyDebug 1.969484
PyDebug 1.790440
PyDebug 1.392636
PyDebug 1.969484
PyDebug 1.790440
PyDebug 1.392636
PyDebug 1.969484
PyDebug 1.790440
PyDebug 1.392636
PyDebug 1.969484
PyDebug 1.790440
PyDebug 1.392636
iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  5.1340941e+01 3.33e-16 4.64e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
PyDebug 1.883636
[...many more lines of this and similar ones...]
PyDebug 35.356713
  21  4.5426289e+00 1.62e-09 1.05e-08  -8.6 1.03e-04    -  1.00e+00 1.00e+00h  1
  22  4.5426289e+00 6.55e-10 4.32e-09  -9.0 6.55e-05    -  1.00e+00 1.00e+00h  1

Number of Iterations....: 22

                                   (scaled)                 (unscaled)
Objective...............:   4.5426289179813661e+00    4.5426289179813661e+00
Dual infeasibility......:   4.3226662511009695e-09    4.3226662511009695e-09
Constraint violation....:   6.5500968537968163e-10    6.5500968537968163e-10
Complementarity.........:   1.4991089664955258e-09    1.4991089664955258e-09
Overall NLP error.......:   4.3226662511009695e-09    4.3226662511009695e-09
 
 
Number of objective function evaluations             = 23
Number of objective gradient evaluations             = 23
Number of equality constraint evaluations            = 23
Number of inequality constraint evaluations          = 23
Number of equality constraint Jacobian evaluations   = 23
Number of inequality constraint Jacobian evaluations = 23
Number of Lagrangian Hessian evaluations             = 22
Total CPU secs in IPOPT (w/o function evaluations)   =      0.078
Total CPU secs in NLP function evaluations           =      0.012
 
EXIT: Optimal Solution Found.

**Comment by xuy** [comment]
Fixed in #41
